spring:
  application:
    name: oauth2-resource
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth2_resource?useUnicode=true&characterEncoding=utf-8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: Yanlei2018
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      # 认证服务器hello-spring-security-oauth2-server地址，获取access_token
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
    resource:
      # 需要在认证服务器hello-spring-security-oauth2-server中设置，不拦截（不需要授权的）
      token-info-uri: http://localhost:8080/oauth/check_token
server:
  port: 8081
  servlet:
    context-path: /contents
mybatis:
  type-aliases-package: com.funtl.spring.security.oauth2.resource.domain
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO